# Generated by Django 2.1.3 on 2019-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Post',
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text3',
            field=models.TextField(blank=True),
        ),
    ]
