# Generated by Django 2.1.3 on 2019-03-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeeshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('smoking', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('image1', models.ImageField(upload_to='media/images')),
                ('image2', models.ImageField(blank=True, upload_to='media/images')),
                ('image3', models.ImageField(blank=True, upload_to='media/images')),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
