# Generated by Django 2.1.3 on 2019-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeshop',
            old_name='author',
            new_name='user',
        ),
    ]
