# Generated by Django 2.1.3 on 2019-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0003_auto_20190310_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='image1',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='coffeeshop',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
