# Generated by Django 2.1.3 on 2019-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0004_auto_20190313_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='working_hours_saturday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='working_hours_sunday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='working_hours_weekdays',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
