# Generated by Django 2.1.7 on 2019-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeshop', '0005_auto_20190314_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='voted',
            field=models.TextField(blank=True),
        ),
    ]
